export const userNotes = [
  {
    noteId: '6',
    parentId: null,
    userId: '4',
    title: '你好',
    content: '{"ops":[{"insert":"请问分\\n"}]}',
    isDelete: false,
    createTime: '2022-08-14T16:41:09.034Z',
    modifyTime: '2022-08-14T16:41:09.034Z',
    childNodes: [
      {
        noteId: '7',
        parentId: '6',
        userId: '4',
        title: 'afvawe',
        content:
          '{"ops":[{"insert":"wefa\\n\\n\\n\\n"},{"attributes":{"width":"441"},"insert":{"image":"http://localhost:8001/files/4-1661165675444.png"}},{"insert":"\\n\\nqewfq "},{"attributes":{"code-block":"plain"},"insert":"\\n\\n"},{"insert":"var = 12341"},{"attributes":{"code-block":"plain"},"insert":"\\n"},{"insert":"\\n"},{"attributes":{"font":"songTi","link":"www.baidu.com"},"insert":"你好"},{"insert":"\\n\\n\\n\\n\\n\\n"}]}',
        isDelete: false,
        createTime: '2022-08-14T16:52:26.431Z',
        modifyTime: '2022-08-23T10:03:37.654Z',
        childNodes: [
          {
            noteId: '8',
            parentId: '7',
            userId: '4',
            title: 'qwerqwe',
            content: '{"ops":[{"insert":"qwefqwe\\n"}]}',
            isDelete: false,
            createTime: '2022-08-14T16:54:54.701Z',
            modifyTime: '2022-08-14T16:54:54.701Z',
            childNodes: [
              {
                noteId: '9',
                parentId: '8',
                userId: '4',
                title: 'wdwe',
                content: '{"ops":[{"insert":"werq\\n"}]}',
                isDelete: false,
                createTime: '2022-08-14T17:32:43.002Z',
                modifyTime: '2022-08-14T17:32:43.002Z',
                childNodes: [
                  {
                    noteId: '10',
                    parentId: '9',
                    userId: '4',
                    title: 'asfawef',
                    content: '{"ops":[{"insert":"wefawef\\n"}]}',
                    isDelete: false,
                    createTime: '2022-08-14T17:34:24.650Z',
                    modifyTime: '2022-08-14T17:34:24.650Z',
                    childNodes: [
                      {
                        noteId: '11',
                        parentId: '10',
                        userId: '4',
                        title: '哇俄方',
                        content: '{"ops":[{"insert":"违法未\\n"}]}',
                        isDelete: false,
                        createTime: '2022-08-14T17:35:12.604Z',
                        modifyTime: '2022-08-14T17:35:12.604Z',
                        childNodes: [
                          {
                            noteId: '12',
                            parentId: '11',
                            userId: '4',
                            title: '为服务器俄方',
                            content: '{"ops":[{"insert":"请问分趣味\\n"}]}',
                            isDelete: false,
                            createTime: '2022-08-14T17:41:14.723Z',
                            modifyTime: '2022-08-14T17:41:14.723Z',
                            childNodes: [],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                noteId: '13',
                parentId: '8',
                userId: '4',
                title: null,
                content: '{"ops":[{"insert":"\\n"}]}',
                isDelete: false,
                createTime: '2022-08-16T16:03:54.359Z',
                modifyTime: '2022-08-16T16:03:54.359Z',
                childNodes: [
                  {
                    noteId: '14',
                    parentId: '13',
                    userId: '4',
                    title: null,
                    content: '{"ops":[{"insert":"\\n"}]}',
                    isDelete: false,
                    createTime: '2022-08-16T16:03:58.242Z',
                    modifyTime: '2022-08-16T16:03:58.242Z',
                    childNodes: [],
                  },
                ],
              },
              {
                noteId: '16',
                parentId: '8',
                userId: '4',
                title: '医疗天天跌',
                content:
                  '{"ops":[{"insert":"加仓\\n\\n"},{"attributes":{"font":"system"},"insert":"ewfqwefqwef"},{"insert":"\\n"}]}',
                isDelete: false,
                createTime: '2022-08-16T16:10:21.596Z',
                modifyTime: '2022-08-18T07:14:56.848Z',
                childNodes: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
export const allSpaces = [
  {
    id: 6,
    userId: '4',
    spaceId: '10',
    title: '正心谷FE',
    roleList: '100@10',
  },
];

export const spaceNotes = [
  {
    noteId: 'l7fsctim',
    parentId: null,
    spaceId: '10',
    creator: '7',
    modifier: '7',
    title: '1234',
    content: '{"ops":[{"insert":"erwer\\n"}]}',
    isDelete: false,
    deleter: null,
    createTime: '2022-08-30T06:05:42.441Z',
    modifyTime: '2022-09-08T11:28:36.679Z',
    childNodes: [
      {
        noteId: 'l7g5dzax',
        parentId: 'l7fsctim',
        spaceId: '10',
        creator: '7',
        modifier: '4',
        title: '阿斯顿发我',
        content: '{"ops":[{"insert":"qwerqwer\\n"}]}',
        isDelete: false,
        deleter: null,
        createTime: '2022-08-30T12:10:31.550Z',
        modifyTime: '2022-10-22T07:53:25.636Z',
        childNodes: [],
      },
    ],
  },
  {
    noteId: 'l7rukcxy',
    parentId: null,
    spaceId: '10',
    creator: '7',
    modifier: '7',
    title: null,
    content: '{"ops":[{"insert":"fsdvsvs\\n"}]}',
    isDelete: false,
    deleter: null,
    createTime: '2022-09-07T16:40:47.612Z',
    modifyTime: '2022-09-08T11:28:44.245Z',
    childNodes: [],
  },
];

export const note = {
  noteId: 'l7g5dzax',
  parentId: 'l7fsctim',
  spaceId: '10',
  creator: '7',
  modifier: '4',
  title: '阿斯顿发我',
  content: '{"ops":[{"insert":"qwerqwer\\n"}]}',
  isDelete: false,
  deleter: null,
  createTime: '2022-08-30T12:10:31.550Z',
  modifyTime: '2022-10-22T07:53:25.636Z',
};
